# Generated by Django 4.2.5 on 2023-09-23 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('link', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=350)),
                ('meta_des', models.CharField(blank=True, max_length=150)),
                ('thumbnail', models.ImageField(upload_to='thumbs/%Y-%m')),
                ('body', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pub', 'publish'), ('drf', 'draft')], default='pub', max_length=3)),
                ('author', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
