# Generated by Django 4.2.6 on 2023-10-26 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sort', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('link', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=350)),
                ('meta_des', models.CharField(blank=True, max_length=150)),
                ('thumbnail', models.ImageField(upload_to='thumbs/%Y-%m')),
                ('body', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_time', models.PositiveSmallIntegerField()),
                ('publish', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=3, editable=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='sort.category')),
                ('tags', models.ManyToManyField(related_name='posts', to='sort.tag')),
            ],
            options={
                'ordering': ['-create_date', '-update'],
            },
        ),
    ]
