# Generated by Django 4.2.6 on 2023-10-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fiel',
            field=models.FileField(blank=True, null=True, upload_to='file/%Y-%m'),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y-%m'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image/%Y-%m'),
        ),
    ]
