# Generated by Django 4.2.6 on 2023-10-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('pub_email', models.EmailField(blank=True, max_length=150)),
                ('insta_id', models.SlugField(blank=True, verbose_name='Instagram ID')),
                ('tel_id', models.SlugField(blank=True, verbose_name='Telegram ID')),
                ('etaa_id', models.SlugField(blank=True, verbose_name='Etaa ID')),
                ('what_id', models.SlugField(blank=True, verbose_name='Whatsapp ID')),
                ('twitt_id', models.SlugField(blank=True, verbose_name='Twitt ID')),
                ('Youtube_id', models.SlugField(blank=True, verbose_name='Youtube ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
