# Generated by Django 4.2.6 on 2023-10-26 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('pub_email', models.EmailField(blank=True, max_length=150)),
                ('insta_id', models.SlugField(blank=True, verbose_name='Instagram ID')),
                ('tel_id', models.SlugField(blank=True, verbose_name='Telegram ID')),
                ('etaa_id', models.SlugField(blank=True, verbose_name='Etaa ID')),
                ('what_id', models.SlugField(blank=True, verbose_name='Whatsapp ID')),
                ('twitt_id', models.SlugField(blank=True, verbose_name='Twitt ID')),
                ('Youtube_id', models.SlugField(blank=True, verbose_name='Youtube ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('admin', django.db.models.manager.Manager()),
            ],
        ),
    ]
