# Generated by Django 4.2.6 on 2023-10-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
