# Generated by Django 4.2.6 on 2023-10-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='users/اصغر.jpg', upload_to='users/%Y'),
        ),
    ]
