# Generated by Django 4.2.5 on 2023-09-24 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='status',
            new_name='confirm',
        ),
    ]
